@echo off
REM =====================================================================
REM  MAHANTERP ERP - ONE-CLICK DEPLOYMENT SCRIPT
REM  Run this on the TARGET server as Administrator
REM  It will: install dependencies, restore DB, build & start the app
REM =====================================================================

setlocal enabledelayedexpansion

echo.
echo  ============================================================
echo    MAHANTERP ERP - DEPLOYMENT SETUP
echo  ============================================================
echo.

REM ---------- CONFIGURATION (EDIT THESE BEFORE RUNNING) ----------
set DB_HOST=localhost
set DB_PORT=5432
set DB_NAME=erp_production
set DB_USER=postgres
set DB_PASSWORD=1234
set APP_PORT=3005
set FRONTEND_PORT=4173
set JWT_SECRET=change-me-to-a-strong-secret-key
REM ---------------------------------------------------------------

echo [1/6] Checking prerequisites...
where node >nul 2>&1 || (echo ERROR: Node.js not found. Install from https://nodejs.org & pause & exit /b 1)
where npm >nul 2>&1  || (echo ERROR: npm not found. & pause & exit /b 1)
where pg_restore >nul 2>&1 || (echo WARNING: pg_restore not in PATH. Add PostgreSQL bin to PATH.)
echo       Node.js and npm found.

echo.
echo [2/6] Writing environment config...

REM Write server .env
(
echo # Auto-generated by deploy.bat
echo DATABASE_URL=postgresql://%DB_USER%:%DB_PASSWORD%@%DB_HOST%:%DB_PORT%/%DB_NAME%
echo JWT_SECRET=%JWT_SECRET%
echo PORT=%APP_PORT%
) > server\.env

REM Write frontend .env (build-time - if needed)
(
echo VITE_API_PORT=%APP_PORT%
) > .env.production.local

echo       Environment files written.

echo.
echo [3/6] Restoring PostgreSQL database...
echo       Creating database "%DB_NAME%" (ignore error if already exists)...
set PGPASSWORD=%DB_PASSWORD%
createdb -h %DB_HOST% -p %DB_PORT% -U %DB_USER% %DB_NAME% 2>nul
echo       Restoring from backup...
pg_restore -h %DB_HOST% -p %DB_PORT% -U %DB_USER% -d %DB_NAME% --no-owner --role=%DB_USER% -v "backup\database.dump" 2>>deploy_log.txt
echo       Database restore complete. Check deploy_log.txt for details.

echo.
echo [4/6] Installing server dependencies...
cd server
call npm install --production
echo       Running Prisma schema sync...
call npx prisma db push --accept-data-loss
cd ..
echo       Server dependencies installed.

echo.
echo [5/6] Building frontend...
call npm install
call npm run build
echo       Frontend built to .\dist\

echo.
echo [6/6] Starting services...
echo       Starting backend server on port %APP_PORT%...
start "MahanterERP-Backend" /min cmd /c "cd server && npm run start"

echo       Waiting 3 seconds for backend to start...
timeout /t 3 /nobreak >nul

echo       Starting frontend preview on port %FRONTEND_PORT%...
start "MahanterERP-Frontend" /min cmd /c "npm run start"

echo.
echo  ============================================================
echo    DEPLOYMENT COMPLETE!
echo    Frontend: http://localhost:%FRONTEND_PORT%
echo    Backend:  http://localhost:%APP_PORT%
echo  ============================================================
echo.
echo  To run automatically on Windows startup, run:
echo    setup-autostart.ps1
echo.
pause
